kind: Service
apiVersion: v1
metadata:
  name: kubernetes-configmap
spec:
  type: LoadBalancer
  selector:
    app: kubernetes-configmap
  ports:
    - name: http
      protocol: TCP
      # ELB's port
      port: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-configmap
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-configmap
  template:
    metadata:
      labels:
        app: kubernetes-configmap
    spec:
      containers:
        - name: kubernetes-configmap
          image: mbb216/kubernetes-configmap:latest
